import {jvm} from './jvectormap'
import './abstract-element.js'
import './svg'
import './vml'
import './vector-canvas.js'
import './simple-scale.js'
import './ordinal-scale.js'
import './numeric-scale.js'
import './color-scale.js'
import './legend.js'
import './data-series.js'
import './proj.js'
import './map-object.js'
import './region.js'
import './marker.js'
import './map.js'
import './multimap.js'

export default jvm
